from .carrier_examples import (
    PROCUREMENT_HIGH_RISK,
    PROCUREMENT_HIGH_VALUE,
    PROCUREMENT_STANDARD,
    REFERENCE_PROFILES,
)

__all__ = [
    "PROCUREMENT_HIGH_RISK",
    "PROCUREMENT_HIGH_VALUE",
    "PROCUREMENT_STANDARD",
    "REFERENCE_PROFILES",
]
