"""Machine-readable route invalidation and pruning reasons."""

from enum import Enum


class RouteReasonCode(str, Enum):
    ROUTE_AUTHORITY_INVALID = "ROUTE_AUTHORITY_INVALID"
    ROUTE_POLICY_INVALID = "ROUTE_POLICY_INVALID"
    ROUTE_MAL_INADMISSIBLE = "ROUTE_MAL_INADMISSIBLE"
    ROUTE_EVIDENCE_INSUFFICIENT = "ROUTE_EVIDENCE_INSUFFICIENT"
    ROUTE_SEMANTIC_INTEGRITY_FAILED = "ROUTE_SEMANTIC_INTEGRITY_FAILED"
    ROUTE_CONSENT_INVALID = "ROUTE_CONSENT_INVALID"
    ROUTE_PRIVACY_INVALID = "ROUTE_PRIVACY_INVALID"
    ROUTE_BUDGET_EXCEEDED = "ROUTE_BUDGET_EXCEEDED"
    ROUTE_DEADLINE_UNREACHABLE = "ROUTE_DEADLINE_UNREACHABLE"
    ROUTE_RISK_EXCEEDED = "ROUTE_RISK_EXCEEDED"
    ROUTE_IRREVERSIBILITY_EXCEEDED = "ROUTE_IRREVERSIBILITY_EXCEEDED"
    ROUTE_HUMAN_CHECKPOINT_MISSING = "ROUTE_HUMAN_CHECKPOINT_MISSING"
    ROUTE_EXECUTION_CAPABILITY_MISSING = "ROUTE_EXECUTION_CAPABILITY_MISSING"
    ROUTE_DEPENDENCY_UNREACHABLE = "ROUTE_DEPENDENCY_UNREACHABLE"
    ROUTE_STATE_STALE = "ROUTE_STATE_STALE"
    ROUTE_DUPLICATE = "ROUTE_DUPLICATE"
    ROUTE_DOMINATED = "ROUTE_DOMINATED"
    ROUTE_HIGHER_END_TO_END_LATENCY = "ROUTE_HIGHER_END_TO_END_LATENCY"
    ROUTE_HIGHER_COST_EQUIVALENT_OUTCOME = "ROUTE_HIGHER_COST_EQUIVALENT_OUTCOME"
    ROUTE_REQUIRES_STEP_UP = "ROUTE_REQUIRES_STEP_UP"
    ROUTE_INVALIDATED_BY_DRIFT = "ROUTE_INVALIDATED_BY_DRIFT"
    ROUTE_GRAPH_INVALID = "ROUTE_GRAPH_INVALID"
    ROUTE_NO_VALID_CANDIDATE = "ROUTE_NO_VALID_CANDIDATE"
    ROUTE_REPLAN_DEFERRED = "ROUTE_REPLAN_DEFERRED"
    ROUTE_REPLAN_BUDGET_EXHAUSTED = "ROUTE_REPLAN_BUDGET_EXHAUSTED"
    ROUTE_RECOVERY_UNAVAILABLE = "ROUTE_RECOVERY_UNAVAILABLE"
    ROUTE_RETRY_EXHAUSTED = "ROUTE_RETRY_EXHAUSTED"
    ROUTE_CANCELLED = "ROUTE_CANCELLED"
    ROUTE_EXPIRED = "ROUTE_EXPIRED"
    ROUTE_AUTHORITY_HOLDER_UNAVAILABLE = "ROUTE_AUTHORITY_HOLDER_UNAVAILABLE"


__all__ = ["RouteReasonCode"]
