"""Compatibility wrapper exposing kernel's external_adapters API from valo_external_adapters."""

from ..ecosystems import (
    ECOSYSTEM_MANIFESTS,
    EcosystemAdapterManifest,
    ExternalAdapterEvidence,
    ExternalAdapterExecutionRequest,
    ExternalAdapterRole,
    ExternalEcosystem,
    ExternalStateClass,
    ExternalStateObservation,
    build_circle_usdc_request,
    build_coinbase_x402_request,
    build_kyriba_state_observation,
    build_open_banking_payment_request,
    build_sap_state_observation,
    build_sepa_credit_transfer_request,
    record_external_adapter_evidence,
    seal_external_state_observation,
)
from ..payments import (
    FORBIDDEN_PROVIDER_OVERRIDE_KEYS,
    PROVIDER_MANIFESTS,
    ExternalAdapterManifest,
    ExternalExecutionBinding,
    ExternalPaymentProvider,
    ExternalProviderRequest,
    ProviderOutcomeDisposition,
    build_mastercard_agent_pay_request,
    build_stripe_agentic_payment_request,
    build_swift_cbpr_plus_request,
    build_visa_trusted_agent_request,
    record_provider_evidence,
    seal_external_execution_binding,
)

__all__ = [
    "ECOSYSTEM_MANIFESTS",
    "FORBIDDEN_PROVIDER_OVERRIDE_KEYS",
    "PROVIDER_MANIFESTS",
    "EcosystemAdapterManifest",
    "ExternalAdapterEvidence",
    "ExternalAdapterExecutionRequest",
    "ExternalAdapterManifest",
    "ExternalAdapterRole",
    "ExternalEcosystem",
    "ExternalExecutionBinding",
    "ExternalPaymentProvider",
    "ExternalProviderRequest",
    "ExternalStateClass",
    "ExternalStateObservation",
    "ProviderOutcomeDisposition",
    "build_circle_usdc_request",
    "build_coinbase_x402_request",
    "build_kyriba_state_observation",
    "build_mastercard_agent_pay_request",
    "build_open_banking_payment_request",
    "build_sap_state_observation",
    "build_sepa_credit_transfer_request",
    "build_stripe_agentic_payment_request",
    "build_swift_cbpr_plus_request",
    "build_visa_trusted_agent_request",
    "record_external_adapter_evidence",
    "record_provider_evidence",
    "seal_external_execution_binding",
    "seal_external_state_observation",
]
